### ISSUE TITLE
Criar página Comece Agora

### ISSUE THREAD

**Issue by pedrosrk** [nextimecode/f02-web-academia#7]
Ao clicar em “Comece Agora” no menu superior o usuário deverá ser direcionado para os planos que são disponibilizados no site, tais planos podem ser divididos em três categorias como é mostrado na imagem ao lado.

Esforço:
Web [1]  
Análise []

**Comment by marcuslamounier** [comment]
No modelo, essa página é apenas um redirecionamento.
